import { describe, expect, it } from "vitest";
import fc from "fast-check";
import { AI_Difficulty, GameStatus, PlayerSymbol, WINNING_COMBINATIONS, oppositeSymbol } from "@/game/constants";
import { getAIMove } from "@/game/ai";
import {
  checkWinner,
  freshGameState,
  getValidMoves,
  isValidMove,
  makeMove,
  type Board,
  type GameState,
} from "@/game/logic";

// Property suite for the pure game domain (work:481). The domain is
// *reachable* states — generated by replaying random legal moves through
// makeMove itself, never by hand-constructing boards — so the invariants
// bind the real game flow, not an imagined board space.

const activeState = (): GameState => ({ ...freshGameState(), gameStatus: GameStatus.ACTIVE });

/** Replay a legal move sequence; returns the final reachable state. */
const replay = (moves: number[]): GameState => {
  let s = activeState();
  for (const m of moves) {
    const next = makeMove(s, m, 1_000);
    if (next === null) return s; // terminal or invalid — sequence ends
    s = next;
  }
  return s;
};

/** Random legal-move sequences over the 3-piece variant. */
const moveSeq = fc.array(fc.integer({ min: 0, max: 8 }), { maxLength: 24 });

describe("game-rule properties", () => {
  it("eviction respects maxMoves — moves lists never exceed it and stay in FIFO order", () => {
    fc.assert(
      fc.property(moveSeq, (moves) => {
        let s = activeState();
        for (const m of moves) {
          const before = s;
          const next = makeMove(s, m, 1_000);
          if (next === null) break;
          for (const sym of [PlayerSymbol.X, PlayerSymbol.O] as const) {
            expect(next.moves[sym].length).toBeLessThanOrEqual(next.maxMoves);
            // Every listed move is that symbol's piece on the board, and vice versa.
            for (const idx of next.moves[sym]) {
              expect(next.board[idx]).toBe(sym);
            }
            const onBoard = next.board.filter((c) => c === sym).length;
            expect(onBoard).toBe(next.moves[sym].length);
          }
          // When the mover was at max, the evicted cell is the previous oldest.
          const mover = before.currentPlayer;
          if (before.moves[mover].length === before.maxMoves) {
            const evicted = before.moves[mover][0];
            expect(next.moves[mover]).not.toContain(evicted);
            expect(next.board[evicted]).not.toBe(mover);
          }
          s = next;
        }
      }),
    );
  });

  it("turns alternate while the game is live and freeze after a winner", () => {
    fc.assert(
      fc.property(moveSeq, (moves) => {
        let s = activeState();
        for (const m of moves) {
          const mover = s.currentPlayer;
          const next = makeMove(s, m, 1_000);
          if (next === null) {
            // Once a winner exists every further move must be rejected.
            if (s.winner !== null) {
              expect(makeMove(s, m, 1_000)).toBeNull();
            }
            continue;
          }
          if (next.winner === null) {
            expect(next.currentPlayer).toBe(oppositeSymbol(mover));
          }
          s = next;
        }
      }),
    );
  });

  it("the AI never emits an occupied or illegal cell on any generated state", () => {
    fc.assert(
      fc.property(moveSeq, fc.constantFrom(PlayerSymbol.X, PlayerSymbol.O), (moves, ai) => {
        const s = replay(moves);
        for (const diff of [AI_Difficulty.EASY, AI_Difficulty.NORMAL, AI_Difficulty.HARD] as const) {
          const move = getAIMove(s, diff, ai);
          if (!isGameActiveFor(s, ai)) {
            expect(move).toBeNull();
          } else {
            expect(move).not.toBeNull();
            expect(isValidMove(s, move as number, ai)).toBe(true);
            expect(s.board[move as number]).toBeNull();
          }
        }
      }),
    );
  });

  it("checkWinner is board-symmetric — a win survives every dihedral transform", () => {
    const cell = fc.constantFrom(PlayerSymbol.X, PlayerSymbol.O, null);
    const boardArb = (
      fc.array(cell, { minLength: 9, maxLength: 9 }) as fc.Arbitrary<Board>
    ).filter((b) => {
      // Unreachable multi-winner boards are outside the contract: checkWinner
      // returns the first combo in scan order, so a board where BOTH symbols
      // complete a line makes the answer order-dependent under transforms.
      const wins = (sym: PlayerSymbol) =>
        WINNING_COMBINATIONS.some(([a, c, d]) => b[a] === sym && b[c] === sym && b[d] === sym);
      return !(wins(PlayerSymbol.X) && wins(PlayerSymbol.O));
    });
    const transforms: Array<(b: Board) => Board> = [
      (b) => b,
      // (r,c) -> (c, 2-r) etc. for the 8 symmetries of the square
      (b) => rot90(b),
      (b) => rot90(rot90(b)),
      (b) => rot90(rot90(rot90(b))),
      (b) => flipH(b),
      (b) => rot90(flipH(b)),
      (b) => rot90(rot90(flipH(b))),
      (b) => rot90(rot90(rot90(flipH(b)))),
    ];
    fc.assert(
      fc.property(boardArb, (board) => {
        const base = checkWinner(board).winner;
        for (const t of transforms) {
          expect(checkWinner(t(board)).winner).toBe(base);
        }
      }),
    );
  });

  it("HARD takes an immediate win whenever one exists", () => {
    fc.assert(
      fc.property(moveSeq, (moves) => {
        const s = replay(moves);
        const ai = s.currentPlayer;
        fc.pre(isGameActiveFor(s, ai));
        const winning = getValidMoves(s.board).filter(
          (i) => makeMove(s, i, 1_000)?.winner === ai,
        );
        fc.pre(winning.length > 0);
        const move = getAIMove(s, AI_Difficulty.HARD, ai);
        expect(winning).toContain(move);
      }),
    );
  });
});

const isGameActiveFor = (s: GameState, ai: PlayerSymbol): boolean =>
  s.gameStatus === GameStatus.ACTIVE && s.winner === null && s.currentPlayer === ai;

const idx = (r: number, c: number): number => r * 3 + c;
const rot90 = (b: Board): Board => {
  const out = b.slice() as Board;
  for (let r = 0; r < 3; r++) for (let c = 0; c < 3; c++) out[idx(c, 2 - r)] = b[idx(r, c)];
  return out;
};
const flipH = (b: Board): Board => {
  const out = b.slice() as Board;
  for (let r = 0; r < 3; r++) for (let c = 0; c < 3; c++) out[idx(r, 2 - c)] = b[idx(r, c)];
  return out;
};
